name = "pictofrontend-proxy"
main = "cloudflare/worker.mjs"
compatibility_date = "2026-03-01"
workers_dev = false

routes = [
  { pattern = "pictofrontend.com/*", zone_name = "pictofrontend.com" },
  { pattern = "www.pictofrontend.com/*", zone_name = "pictofrontend.com" }
]

[[d1_databases]]
binding = "DB"
database_name = "pictofrontend-db"
database_id = "6bcf99a1-3b2d-48c3-890d-c3369287ed47"

[vars]
DOMAIN = "pictofrontend.com"
